version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/ai-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/auth"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/batch-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/gateway"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/mail-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/problems-service"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
