spring:
  application:
    name: auth
  security:
    oauth2:
      authorizationserver:
        client:
          client-1:
            registration:
              client-id: "client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8000/login/oauth2/code/spring"
              scopes:
                - "user.read"
                - "user.write"
                - "openid"
            require-authorization-consent: true



  sql:
    init:
      mode: always
server:
  port: 8002
logging:
  level:
    org.springframework.security: TRACE