spring:
  application:
    name: batch-service
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://SUPER-BUSH
    username: owner
    password: DONTSTEALMYPASS
#  batch:
#    jdbc:
#      initialize-schema: "always"
